version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: on-failure

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: on-failure

  backend:
    image: carkazm/designcollab_backend:latest
    entrypoint: /app/entrypoint.sh
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/docs/
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=designers.settings
    restart: on-failure

  daphne:
    image: carkazm/designcollab_backend:latest
    entrypoint: /app/entrypoint_daphne.sh
    command: daphne -b 0.0.0.0 -p 8001 designers.asgi:application
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/docs/
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=designers.settings
    ports:
      - "8001:8001"
    restart: on-failure

  frontend:
    image: annakharatova/design-collab:latest
    volumes:
      - frontend:/app/build/

  nginx:
    image: nginx:1.25.0-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - daphne
    restart: on-failure

volumes:
  frontend:
  postgres_data:
  static_value:
  media_value:
  redoc:
  redis_data:
