# Generated by Django 4.2.1 on 2023-10-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sphere',
            options={'ordering': ['name'], 'verbose_name': 'Сфера', 'verbose_name_plural': 'Сферы'},
        ),
        migrations.AddField(
            model_name='sphere',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
