# Generated by Django 4.2.1 on 2023-11-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_order_options_alter_order_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="specialization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.specialization",
            ),
        ),
    ]
